services:

    api:
        build:
            context: ./api
        depends_on:
            - database
            - object-store
            - message-broker

    worker:
        build:
            context: ./worker
        depends_on:
            - database
            - object-store
            - message-broker

    database:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    object-store:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address ":9001"

    message-broker:
        image: rabbitmq
        ports:
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
